---
language: ruby
bundler_args: --without system_tests
script: "bundle exec rake validate && bundle exec rake lint && STRICT_VARIABLES=no bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 4.0"
branches:
  only:
    - master
